In [1]:
from sklearn.datasets import load_iris
import numpy as np
from sklearn import tree

In [2]:
iris=load_iris()

In [3]:
print (iris.feature_names)
print (iris.target_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']


In [4]:
print (iris.data[0])
print (iris.target[0])
test_idx=[0,50,100]

[5.1 3.5 1.4 0.2]
0


In [5]:
#create training data
train_target=np.delete(iris.target,test_idx)
train_data=np.delete(iris.data,test_idx,axis=0)

In [6]:
# crating test Data
test_target=iris.target[test_idx]
test_data=iris.data[test_idx]


In [7]:
clf=tree.DecisionTreeClassifier()
trainClf=clf.fit(train_data, train_target)

In [8]:
print (test_data)
print (test_target)

[[5.1 3.5 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.3 3.3 6.  2.5]]
[0 1 2]


In [9]:
print (trainClf.predict(test_data))

[0 1 2]


In [ ]:
!conda install graphviz

In [1]:
! pip3 install graphviz

In [2]:
!pip3 install pydot